spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=PROJECT_MANAGER_1;encrypt=false
    username: api_user
    password: Test1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true